{
	"data": "ENC[AES256_GCM,data:kkn+MjdfTZcLOvqZuUChcyU9xwQ7SpQPIxcouVAJ2+TrZ9AsAQ5GADDWUmuA82A1j1gmD6aMnHAJLd3Fgq1S31uVg5PLuiCoD28C8lOUrv6OvI1z6KsGgkaMsQz5/G5A1w5BAhuasMlfJj5HkdDzFB1SYJD6w8a2ygBmuMLSuJqOtvc/ckwGS3+8Zu6Ile03TQ/TM0QFM5Ujq2fAiDH//juEe32WBaPCkZa8GeHclyThgzRDH9f7+nCP8Eg5c4lGvwQdIbeVHII70Vt/Jm2i8SIH+IAbak+qMz/+ZMgWv4vjjOaOfb3cu9EE08JkTBt3pla9EPm8U01MPwfbln5LjEzGR19M,iv:hV3pZ8QHhC5dAyT8RwF55O7X6mVbQ3HFujmCRtip0/I=,tag:jfGUbLxGPUM6jW42/Ba/tA==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGSmYzQWxVRGlLYmdHeDJD\nZktTNzF0ZDFIc0VkbjhRcDBRWFVPeGgyYkcwCnp0cWFWNWlXbWVPVFF1VTBtNnh2\nVVcwVHhZbEIwOHZZVEdLVFk0RU85Mk0KLS0tIEd4MlZWMzF1KzY2MFl1Z0txaXNu\nVmVCcFB6WktBN1E1Vjlta2xSSGN3NDgKkwCNKe6oe89tOaWA98NdRmupvJrlpGvr\n++j2JArwRNAF+0tC28G1quReLiPG/Eb1CqacobdeLvE+HxgqZPpK1w==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1efn67qrhcfhdjycg0sckmnpytcm765ndwys0zfg8dth2lqqss93qk8tsjd"
			}
		],
		"lastmodified": "2026-06-13T23:08:13Z",
		"mac": "ENC[AES256_GCM,data:3NVnplk7HMcLJKjUGdvi/8Xc93qQ0A2UpUiKNDCAAXwIOWfSEN8ZuYRPc8u1X7csNcxqsula2928dfi/pdbKdN7CW2fOl6XyERoThNjxzPewAME3HUNHwf8XbnTFwubMkoq9UZMHkXD0yqe/oQdjmfxbL+CcQcyoscjSQKJB7Ac=,iv:y4DRQaMO+qShh+avAd1E/JwkE4+dTLUt0c4mTXaAf1s=,tag:0xDKEQVBGZHCpIgBv6huMg==,type:str]",
		"version": "3.13.1"
	}
}
