{
	"data": "ENC[AES256_GCM,data:yWh3KA5m9vvzLDByO3hoBPy7Wc6wZCw+3WfTgLfq2DwIrBqPFa83RqC4NJ1F3yAJA3LAKj4PNLTMykCePyGfj6zRcUp8dwRHIzN/6PoC6cR+WJe5UN6udNIPOPQnq1y4RPPJwt/iwWZEBHbFCr8nHUGXRbNyIPOcjWt7D/mH/ofvBJOT5jW5KhcK6kKhrbvSSRC16GrotSgJlE1iWvMMPakQq6BGI7qO2BsPZNv+u+eOV5viQ/jmyAwPPAJEVABTnPyxIh4rpmslqjR8i12RmfN+p6Sj25p6pUsR7bLQyMLgyLtXp3c6odScxEuED3dhUndto64o/5lOqxtg3A==,iv:lGgieaAHsEdmOoRSlFL8WvUXMBcpsXU0FDyK5e3NjqA=,tag:iKWqxed/ui/Py/6Ddmzz3w==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArZUxncWV2U3M1dWkwS3VF\nL1oyQVJSWkNqOUVpL0pKUHNMR2IzT2FDa0RnCkRiZnhuYWxkYTNzbVROSGJOa1pE\nbGFya2lPRmRXZGE5YlNkaFFSVnoyMEUKLS0tIEk1aUtRdTdMbGswaFdudENOZ09T\nbXoxNXJmMGZPSFVyQ3ZLQUNZbW9DSE0K5YukHhTctx7AHtk1l3BeqID9LT0kR6t0\ns3ZTH+yInT2g5IlZndp1ulLsQvU+zBoFZ+QdrdXW5sQBWiNxPHctlQ==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1efn67qrhcfhdjycg0sckmnpytcm765ndwys0zfg8dth2lqqss93qk8tsjd"
			}
		],
		"lastmodified": "2026-05-31T22:43:34Z",
		"mac": "ENC[AES256_GCM,data:lOl3r3GC7Pg66h6bdhSpAdTvSSMUYhzOvcdQg5rM6/YnpaMNeacWEwq620Jy3qUULckZpwFM30XxETsESffB9PXjxzwdg9kqvk6gEkc0YwOGp3CQjFQ9YzLQ08GP+TyVtXOg9sgJ+aK+ukpvPTcpShCY9jBdqtBKP0akL9h+j7w=,iv:qprQ4Gq8xRN/tlXtcF7mn1TDbFIH4QP8FFPA7hUyJGs=,tag:cFstPwuHTGozmTb1aEsk+w==,type:str]",
		"version": "3.13.1"
	}
}
