{
	"data": "ENC[AES256_GCM,data:CSXw+bnsDHfnraIpn/h4oVkUaC3d/fDRY8HJMR7R4NYQg0kyKiQj2d5SA8ZscUqEleprkEv8nW1wGhr1FyyIYBmpZrOJaIgLoSUfnQ0ikdWcXnrabEgNwK+fEzO2VZYkkedW3JH0UfaLqweDNWeGgdNnhTQh1+03grQHcEcJr1ZBWQ+uYmp1iM2+xDHH4FjFF3E+BUkPZEFACMLZNpM+iN7Z3uwrnX3Jyf10U6wJJkdRxOvfExVhASDrIn0vzQdZ0R3NYJWQUdF8xfOoAvoheZEEcUnpWAYTrpaD3otDSroGSHPPO7xjjhGpDDRzsR+G6kbc8SbkU5qbQf2bDA==,iv:GnVSh6lmsCNwgpJycfZg5/rYKPr8SAS6ibnWAd0dUOE=,tag:IQNIURDsScbWJDx+w3/LNg==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1efn67qrhcfhdjycg0sckmnpytcm765ndwys0zfg8dth2lqqss93qk8tsjd",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhelRIdEdpOGo2NDdoN0Fl\nY0Via2w1WVNzcXViSC9QNG03d0haZTZDY3hrCjRFdkJlZlp5U3hwVEdBTXluMU8x\nazdnWXBJOTA0ME9wZ0NGekFneisrb2MKLS0tIGEzdzJMN3lEZ1N3K2hCWDV3L0tS\naVJ5TVdZMGwyalo4ZC80TzVMVGhYbGcKJroRyy/FwWxFkBQkv+XGIrV/07fefuN5\n9L1uj/+JSDolF18p2i7XCo6rGuj0CU7aWEBaPEw6LIdKCjRPrVZWhg==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-05-18T05:34:01Z",
		"mac": "ENC[AES256_GCM,data:/dE4m3vE+mzdeFIo7zHI1aWsINzpNkZSO/ssjPnsAUP3CDzN496EaiKS+yp6mey/QdRxWAKa1t+7R7DVoXzbY7LLYdzz5FE/FjJhropWkaJ3Mr4zanSo8EQiE4gdm8VW19v6oAfm9FyIK+jTugE2PqVbvwGPvcmhvqvQaKwQaJU=,iv:fnGX0VJ69SzUTGLtcOB6CFKuFOcSPNprf/iPROhBxUw=,tag:SE7DN/VcbFn4+PTuDkOdqg==,type:str]",
		"version": "3.12.2"
	}
}
