version: ENC[AES256_GCM,data:9VZT9aNE,iv:z7WspWR8+pLMwJbVcfT2siO6odWMWLdoH62I+N4OEmo=,tag:+BnZMEqB3zv/RBsJvfxH/A==,type:str]
cache: ENC[AES256_GCM,data:z4vejw==,iv:b6+onV5soWc5u6S1Y0zNCwM9kxZVSXMfSBjMPhzjzA4=,tag:t+X9Uo4jQz4OX9OyGe6aIg==,type:bool]
endpoints:
    custom:
        - name: ENC[AES256_GCM,data:qn7iqobfJlFqKs4=,iv:WMoNhElbhoL0HgBEoR1YDuzwMSk5jJfQWDxt9/AyL4c=,tag:VldZOTxmdSpKsF9f8VraKw==,type:str]
          apiKey: ENC[AES256_GCM,data:WovVfW9Qqmm8o738UPyVesFUXg==,iv:vVfU0nPu65KOx5J8uBKveuuXLdnznAJunR/O4kjCjfs=,tag:iYvXWx270Wr9lczIYCKGuw==,type:str]
          baseURL: ENC[AES256_GCM,data:uVKg/ZpoTvKW3cuL/jtuf7aCwEYxrWwklqGZZ1c=,iv:MBw1rEDD7b29SYUq9W0kUoOAnJsdsgDajtlltruW1xc=,tag:MIRZaRUq2nrIRo3KD8OIZA==,type:str]
          modelDisplayLabel: ENC[AES256_GCM,data:13aVeFLveXXjyKQ=,iv:Hl8lz1KtJ54jcQsPydW0W1Swb6YiZDACgr2QAkK2gXs=,tag:7S8u2yf/ceO3Xgioyz6p1A==,type:str]
          titleConvo: ENC[AES256_GCM,data:6QWmIw==,iv:LPxmnLBqlkBrGg7XoaxlglIXKOWE6qoCQ877qjZYfS0=,tag:Tg9ENiyBnC9ag/JzT438Xw==,type:bool]
          titleModel: ENC[AES256_GCM,data:r9rTx9czhYto0c51ABx3NMc=,iv:pYIoSywapMows5ZgU4bw+j9Le1UKPgyqXHCWf3oE/jI=,tag:rWIoD33UHjj0r7XW11ugaw==,type:str]
          models:
            fetch: ENC[AES256_GCM,data:VXgnYA==,iv:pmJphFSHMokamepxngmrMLduSvIv0I5Zo7GOiVEuiL4=,tag:W4zi/qnglcWn2noMCMvbeg==,type:bool]
            default:
                - ENC[AES256_GCM,data:ROiRiNnwbiOfl11Ke0mV9/I=,iv:9IRzuFlX7BUo2ipQf1fF6s56QFMzhNVUwC3yEERuppI=,tag:Qm92B2e43P/GUdQXm1uEAA==,type:str]
mcpSettings:
    allowedDomains:
        - ENC[AES256_GCM,data:3KAQq8DvYE1mfkxB,iv:72JfvpYjvAUJn/S7mG9hjUYpyEQ4DW7cjGsRjw+gap8=,tag:WbGgNxuPcqDljw0KmEju4g==,type:str]
        - ENC[AES256_GCM,data:EHOAtjJq2iNMb1pt,iv:6WvY1MLbWIrBNTQ+gezaDubftR6Pkplx4NgZqkr2Qd0=,tag:DVtXSrKQls0qefJH4tMPHA==,type:str]
        - ENC[AES256_GCM,data:VB2kiKBnoxWe2w==,iv:4qPWPmqEF7fUp5OKjxW/CzvR1yyodomrDytY+IX0aCg=,tag:sGDSUItllcuWCeXl0qwf2g==,type:str]
        - ENC[AES256_GCM,data:SD1n5aFZV2Ffpw==,iv:CvSpEtPqx5th4PyRrmIi4EOWUqYQ7pnXNi52bkyaW4c=,tag:zbrFuPKhpz3j8btS7ZWMow==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhYjNGRmhFQVFqM2FEYWxj
            TVkyNmFZcHpPZjk2bjhwc25CWTZlT29lRzBNCjBvS1JNSWQrOVk3Q29naE1sT2JR
            WGR4Y0VoblN6MUQ4U3YwbFNERkdQNWcKLS0tIHFGRVFZSG9COW1uc2hlcGNldEZU
            RkFvZmJDaG5BNnpKYzRRZis0UjlROWMKBPzocNCT7fSNafDZ+SIcZSONy0KDft3N
            TUIXxVi/FM0WjvcKiLAuDi86sNDd5RWAUJ2UBPlqR9f6o38mN5P8pQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1efn67qrhcfhdjycg0sckmnpytcm765ndwys0zfg8dth2lqqss93qk8tsjd
    lastmodified: "2026-06-10T22:02:19Z"
    mac: ENC[AES256_GCM,data:W3fzN+8XL+GQbL+s4k0iKeLEE5drstB+oBcfQBEeW42kY8tlN++X9QJ+IC+UDOov4z9IzGyxyB8vLo4bBZgbcORZkM6IJa7KgDMdD+7dHg8u/K4x0HrIm+E4X/QLaK5h0aVGWzj9TU+5BmXwo458+1zqJyeqLZU/cgOJuPdxktA=,iv:6McskFVBHBDLxc4qqwBqqIrNMeVBwXOqBF59897VB0c=,tag:CqBzpw2L6kBFaVtET3Xm1Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
