{
	"data": "ENC[AES256_GCM,data:0fPXRITPfGqmt8HwbV1fWoKiNHsSlLnEbj0TXkn6x58ML9R47wZKC+J2qQ==,iv:GjVcWxRziBlH8gqCWJITrc9e18/aQi5f/fWQCei33/0=,tag:nqFKN+jYRyM9xQwXquKBVg==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBya1I4WGZoS1lNVjExWUlD\nT3hWeFRQV3RMWUIyRmNhcU9SY1d5cm9MYnlvCmd3aTFJZWFrd3pvS1c2SEtXVHdM\nSlU3L0szaFlsWm8ydkgwTXg2Vm9DTU0KLS0tIEhNekd4VXVmZnJreXRUZ0I1WTBE\nSG9wN0hnWnpoQlQzdk5COVZyMnI0SzgKgzWWNAQu2TkwlJZilLIdU3T+Urv6Qvge\nwtGXshpHjtVxJSfDyykTaVNKmrIiEnnLYPE2x/JoaDlUtqia3K8xcw==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1efn67qrhcfhdjycg0sckmnpytcm765ndwys0zfg8dth2lqqss93qk8tsjd"
			}
		],
		"lastmodified": "2026-07-23T23:16:24Z",
		"mac": "ENC[AES256_GCM,data:9i8PtBJNYh80pUbGA/+DsndB54JJ9hWS69iSw70NQxDznZQNXOpR1Zol5eMB6wBQlz0RWue2B3CaiQysvD+4EV3PruoSaS65VcFZP0+RuD2PXiey8qVS6EFt4gZpLfa9xZJ0tZTEpcSuOA6Nn2TB0XmVpo5WKAgn9dd64ymdzg8=,iv:ijzLyM0wJ2eCDDsV5J2It3NRirBaEdF0fMcyz7k4tzQ=,tag:l0EgKRcSRi/5qE54yJwC3A==,type:str]",
		"version": "3.13.2"
	}
}
