{
	"data": "ENC[AES256_GCM,data:Y0oOV1XWZZ0F7Z1DpLodYWTCVnSf8c2GAulAccrOFUEqnYyaCvmhOrNDas+3pz1wyOgM1yb5YO+lVgsB8Q==,iv:6/4sMHCyTyKvXl30a1aN02zoD0DfxAgellPnnkjZgQ8=,tag:N6mIZQpCUqbElRGeICOHlQ==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNR1NsVWFhQllieVIrSFFH\nTi91cEl5OE96aVZkTFdGUXhRUjYyYnZyTXo4Cm13dGl3Z2xCNlNyZ29Hb1pLNGFj\nbWR0d0NaTk1vS1J6SWo2S2pUU3ZDZTAKLS0tIEhBTmlNSVZxK09adEhNSlh0bHhl\nNUFOTnZGU3Fxbk5SbTFTZUs5eDFoejAK961ex8ZWtgB33h8nXQeMldW03gLFeqB/\nt8hs/zbfj3rUJ342AU0jMOrmTSawtOzozxf/dcjxd6OCaTZ+94sfaA==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1efn67qrhcfhdjycg0sckmnpytcm765ndwys0zfg8dth2lqqss93qk8tsjd"
			}
		],
		"lastmodified": "2026-07-23T23:16:24Z",
		"mac": "ENC[AES256_GCM,data:CXhmqgD+oclcu8koHCkpKIeh20OiLuqnA8Dp9qG1TbeTPiZKH9YsKCVG2bwYiHioqcOxncamPiUJNoYRf3PK2gcrV5H6o+gBv6nsfIYCDUI0vbL6819BhWIHDenPeAq/bitL+4jVwWc3XAWLRk3inEJGxngnTQdqSFhYC56bYpo=,iv:U+nAquVHmGikqnm4b1UWDV5wgeqFbWzFlGydrvHCXJg=,tag:SRZvA79eFLrvg52f3vAWIg==,type:str]",
		"version": "3.13.2"
	}
}
