{
	"data": "ENC[AES256_GCM,data:Fc2eT7FhSH58B6dsf6AgUe4Aj6DYlf8HBMbHGj0le0ROS62rvDzcL5tieQNxPZQaGPTdxmLPE8I5pY7J+w==,iv:ATkrYNe+Gn74wrqHxVcuDD+4UnB8Qy36Wxd0yZooxo4=,tag:KZqRtO59lAbb0Uj7rL2ZZg==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOSGF5U1BIbjFLWDJyR0J0\nUXZnN3ZuVkpQTDNTaU5OY2w3MWVRSER4SGlVCkNhOHYzOE1oRmNJV1R6MEgwLzhL\nSVU5ZzlvWDI1Nmpwb3BwcEtLREluZ3cKLS0tIDE3Wm1TTXlsVGliVnpPTEtRN2Rv\nMjIvU0RIeXBhTlVpcmhseEh6TXRJWlkK1TRnCKHeunkzmTimWmaj5zwD/H/lejVx\nALIiQiw7EqQ5nPO7ghZANwKXNC75uvD0Jbj9HtiinSKBoNpc4sRmqQ==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1efn67qrhcfhdjycg0sckmnpytcm765ndwys0zfg8dth2lqqss93qk8tsjd"
			}
		],
		"lastmodified": "2026-06-12T04:59:38Z",
		"mac": "ENC[AES256_GCM,data:Xquff/+8ukJMPIKAnA0TbJwLBIt0hMO6C1Kk95x2lic/KABpI2OEWqA5CBaTeeN0JagPZgyzV6qflOgl/+1wz+TgHNHIuaz3i+fsN24+0Apfa9Q+LP0G10xmNKrP1xG98nhfNUsYzkgf5/TYqlZNbAz108blGh/qWjV0w/tUMuw=,iv:O8GJznAt/5Bmj6YAKYPd4cpPAJKyZ7Kw9AqWIsRF/gE=,tag:nREPs8IJaaRUlovGojsSfA==,type:str]",
		"version": "3.13.1"
	}
}
